### ISSUE TITLE
mongoid search error

### ISSUE THREAD

**Issue by gregwebs** [puffer/puffer#12]
I couldn't find any documentation on how to use mongoid.

I added `require 'puffer/orm_adapter/mongoid'` and it started working (although I had to remove a bunch of my model fields). When I ran a search I got the following:

```
$where compile error

2: <h1><%= @title %></h1>
3: 
4: 
5: <% if records.present? %>
6:   <div class="rui-paginator" data-paginator="{total: <%= records.num_pages %>, current: <%= params[:page] || 1 %>, link: {href: '<%= resource.collection_path(:page => '%{page}') %>'}}"></div>
7: 
8:   <%= render :layout => 'table', :locals => {:table_fields => index_fields} do |record| %>

mongo (1.3.1) lib/mongo/cursor.rb:101:in `next_document'
mongo (1.3.1) lib/mongo/collection.rb:251:in `find_one'
mongoid (2.2.0) lib/mongoid/collections/master.rb:25:in `block in find_one'
mongoid (2.2.0) lib/mongoid/collections/retry.rb:29:in `retry_on_connection_failure'
mongoid (2.2.0) lib/mongoid/collections/master.rb:24:in `find_one'
mongoid (2.2.0) lib/mongoid/collection.rb:60:in `find_one'
mongoid (2.2.0) lib/mongoid/contexts/mongo.rb:72:in `blank?'
mongoid (2.2.0) lib/mongoid/criteria.rb:44:in `blank?'
activesupport (3.1.0) lib/active_support/core_ext/object/blank.rb:18:in `present?'
puffer (0.0.29) app/views/puffer/base/index.html.erb:5:in `__home_gweber__rvm_gems_ruby_______p____gems_puffer________app_views_puffer_base_index_html_erb___2998686893773977758_47230160'
actionpack (3.1.0) lib/action_view/template.rb:144:in `block in render'
...
```

**Comment by gregwebs** [comment]
oh, I see in the log now- it is trying to run a SQL like query. Do you have searching setup for mongoDB? I have code for this that I wrote to be able to use Mongoid with admin_assistant

**Comment by pyromaniac** [comment]
Yep, mongoid support is incomplete right now. But should be finished soon. I've planned to use orm_adapter + custom methods for compatibility. Please, give a uri to your solution.

**Comment by gregwebs** [comment]
https://github.com/gregwebs/admin_assistant/blob/master/lib/admin_assistant/search.rb#L21

Actually it is mostly dealing with how an admin_assistant search has different parameters when the search is for any field or just for a specific field, and if it is an OR among fields or an AND. All you have to do is `where(field => regex)`, or use any_of to do an OR search

**Comment by ethank** [comment]
Very interested i monogid support since none of the other admin generators support it.

**Comment by pyromaniac** [comment]
Yep, i interested too )

**Comment by gregwebs** [comment]
there is a fork of rails_admin that has most of the needed Mongoid support.
I have a fork (the earlier link) of admin_assistant that has most of the
needed Mongoid support.

**Comment by ethank** [comment]
Do you have a link for the fork of rails_admin with mongoid support?

**Comment by gregwebs** [comment]
there is a github issue for it- you should look for links on there.

**Comment by pyromaniac** [comment]
Now we have mongoid search support.

**Comment by mgartner** [comment]
@gregwebs in what file did you add `require 'puffer/orm_adapter/mongoid'` to get puffer working with mongoid? Also, I tried using the mongoid fork of rails_admin, but it seems incompatible with rails 3.1. Any suggestions to make it work with the newest version of rails? Thanks for your help - I'm in desperate need of an admin interface that is compatible with mongoid.

**Comment by gregwebs** [comment]
Marcus,

I would recommend you first try the latest version of puffer.

I actually created a config/initializer/puffer.rb file with just that
require. Puffer does not have as many features as admin_assistant, so you
might try my fork, but it is kind of an ugly hack and may just fail on
features i don't use.

Thanks,
Greg

**Comment by pyromaniac** [comment]
Puffer master now has full mongoid support. So you can use it.

About features - puffer is a kind of framework. I try to make if as flexible as possible. You can create any kind of component you need. Components acts like apotomo, so they are self-updatable. I think powerfull components is a killer feature of puffer.

**Comment by gregwebs** [comment]
I wasn't aware of components because the wiki is not linked to from the README !

From the Wiki page I still don't know how components integrate into the rest of the app.
If you could give an example of how to achieve some of the conveniences in other admins with them that would be very helpful. For example, I can drop in a view file _after_form.html.erb that will automatically render content after the form.

**Comment by pyromaniac** [comment]
@gregwebs did you use https://github.com/apotonick/cells or https://github.com/apotonick/apotomo?

And i'm so sorry, i've just started my first really public project, so i'll learn how to write docs )

Maybe http://dl.dropbox.com/u/19461052/cast.mpeg - this cast could help you? It is unfinished right now, has no sound, but i hope, it'll help.

**Comment by gregwebs** [comment]
your docs are very good actually, it is just that components are a more
advanced concept. The screencast really needs some editing & audio, thanks
for sharing now then. I am looking at http://apotomo.de/ which has a lot of
docs.

BTW, This project has a lot of potential, largely due to orm_adapter &
Mongoid support which the others are falling behind on. Maybe components are
also the killer feature, or maybe others can already use cells/aptomo, not
sure.

**Comment by mgartner** [comment]
I've gotten a little bit further with Puffer, but I'm getting an error: `Could not find table 'puffer_users'`. What other setup steps do I need to perform that aren't mentioned in the README?

**Comment by mgartner** [comment]
I'm also seeing and error: `uninitialized constant ActiveRecord`. I removed `require rails/all` and replaced it with 

`require 'action_controller/railtie'
require 'action_mailer/railtie'
require 'active_resource/railtie'` 

in application.rb to take out the ActiveRecord dependency because I shouldn't need it with mongoid, right?

**Comment by pyromaniac** [comment]
Hm, i should share this screencast wider. After finishing )

In puffer you can use any auth system, but by default is uses AM secure_password with AR PufferUser model. I'll try to make this part of puffer more independant. Thanks for report.

**Comment by mgartner** [comment]
Can you make the authentication wiki more clear on how to use your own authentication? Do i just need to add `current_puffer_user` and `has_puffer_access?` methods to my applications_controller.rb? Or is there more required?

**Comment by pyromaniac** [comment]
I wrote an instruction for auth, but found there is docs already ) https://github.com/puffer/puffer/blob/master/lib/puffer/controller/auth.rb

Also please check master, it seems i've fixed `uninitialized constant ActiveRecord` issue

**Comment by mgartner** [comment]
I'm using the most recent code but I'm still getting the `uninitialized constant ActiveRecord` error. Any ideas?

**Comment by gregwebs** [comment]
@mgartner: can you get your app (a simple hello world perhaps) without puffer to run first? Likely this error has been encountered by other Mongoid users.

**Comment by mgartner** [comment]
I seem to have gotten by the ActiveRecord issue thanks to the latest fix. My next step is to setup the authentication system, either custom or getting the built-in one working with Mongoid. Currently puffer is trying to call an ActiveRecord method on the mongoid object:

`undefined method `find_by_email' for PufferUser:Class`

**Comment by gregwebs** [comment]
You can roll your own admin auth very easily. Add an admin field to your
users, check it in a before filter.

That code that is erroring should be changed to Rails3/Mongoid compatible

```
where(:email => email).first
```

**Comment by pyromaniac** [comment]
Oh, my bad. I'll fix it soon. Also, basic own puffr auth system needs more docs.

**Comment by pyromaniac** [comment]
Fixed, try master.

**Comment by mgartner** [comment]
Ok I got my own auth system working. My next issue is that there seems to be no Mongoid-specific relationship components - ReferencesOne or References Many. I guess I may have to build my own?

BTW, I'm willing to document everything I've done to get up and running with Puffer and Mongoid if I can get to a comfortable stage where almost everything is working.

**Comment by pyromaniac** [comment]
About ReferencesOne or References Many.

Puffer has own type-to-component mapping, https://github.com/puffer/puffer/blob/master/lib/puffer.rb#L62, so you even so i should add new mappings just like this:

```
map_component :references_one, :to => :ReferencesOneComponent
map_component :references_many, :to => :ReferencesManyComponent
```

Mongoid's referenceses api acs like AR's, so we can use the same components. On the other hand this two components are unfinished ) And they are next thing i should finish. The same thing with embeddeds.

**Comment by mgartner** [comment]
The ReferencesOneComponent and ReferencesManyComponent seem to break on Mongoid models because there is no 'foreign_key' field. That's the error I was getting when I tried to use them.

**Comment by pyromaniac** [comment]
Then I'll write own mongoid components. Soon.
